// @license
// Copyright (c) <YOUR_COPYRIGHT_HOLDER>
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_template_version_test.dart.
// coverage:ignore-file

/// The version of the `dna_template` package.
const String dnaTemplateVersion = '0.0.0';
